### PR TITLE
Fix getindex of Fill with Trues in N-D

### LINKED ISSUE #150: getindex with Fill and Trues - ND
Sadly my fix of #148 was not quite general enough to cover all my use cases.

```julia
using FillArrays # v0.11.8

ones(2,3)[trues(2,3)] # works
Ones(2,3)[Trues(6)] # works in v0.11.8 due to recent PR
Ones(2,3)[Trues(2,3)] # fails

ERROR: LoadError: MethodError: getindex(::Ones{Float64, 2, Tuple{Base.OneTo{Int64}, Base.OneTo{Int64}}}, ::Trues{2, Tuple{Base.OneTo{Int64}, Base.OneTo{Int64}}}) is ambiguous. Candidates:
  getindex(x::AbstractArray{T, N}, mask::Ones{Bool, N, Tuple{Vararg{Base.OneTo{Int64}, N}}}) where {T, N} in FillArrays at /Users/fessler/.julia/packages/FillArrays/b7lZG/src/trues.jl:39
  getindex(A::FillArrays.AbstractFill, kr::AbstractArray{Bool, N} where N) in FillArrays at /Users/fessler/.julia/packages/FillArrays/b7lZG/src/FillArrays.jl:184
Possible fix, define
  getindex(::FillArrays.AbstractFill{T, N, Axes} where Axes, ::Ones{Bool, N, Tuple{Vararg{Base.OneTo{Int64}, N}}}) where {T, N}
```

I will see what I can do...

### PR DESCRIPTION
**Pull request by JeffFessler**
Fixes #150 in a more general way that also covers #148.

Limited to `OneTo` axes for simplicity and reasons discussed in #149.
Someone could perhaps generalize in the future if they have a need.

### CODE REVIEW

File: src/trues.jl [hunk 1]
```diff
@@ -44,10 +44,11 @@ function Base.getindex(x::AbstractArray{T,N}, mask::Trues{N, NTuple{N,Base.OneTo
     return x[trues(size(x))] # else revert to usual getindex method
 end
 
-# https://github.com/JuliaArrays/FillArrays.jl/issues/148
+# https://github.com/JuliaArrays/FillArrays.jl/issues/148 and 150
 function Base.getindex(
-    a::AbstractFill{T, 1, Tuple{Base.OneTo{Int}}},
-    b::Trues{1, Tuple{Base.OneTo{Int}}}) where T
-    @boundscheck length(a) == length(b) || throw(BoundsError(a, b))
+    a::AbstractFill{T, N, Tuple{Vararg{Base.OneTo{Int64}, N}}},
```
Comment (dlfivefifty) [inline src/trues.jl:49]:
```suggestion
    a::AbstractFill{T, N, Tuple{Vararg{Base.OneTo{Int}, N}}},
```

File: src/trues.jl [hunk 2]
```diff
@@ -44,10 +44,11 @@ function Base.getindex(x::AbstractArray{T,N}, mask::Trues{N, NTuple{N,Base.OneTo
...
+    b::Trues{N, Tuple{Vararg{Base.OneTo{Int64}, N}}},
```
Comment (dlfivefifty) [inline src/trues.jl:50]:
```suggestion
    b::Trues{N, Tuple{Vararg{Base.OneTo{Int}, N}}},
```

**Review by dlfivefifty — CHANGES_REQUESTED** [review]

File: src/trues.jl (hunk 2 above)
Comment (JeffFessler) [reply src/trues.jl]: oops, sorry you had to suggest this again, just like my previous PR.
i keep just copying the type suggested by julia for resolving the ambiguity...
